# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore aspnetmvcapp.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run:
     #   msbuild  aspnetmvcapp.sln /p:Configuration=Release 
         msbuild  aspnetmvcapp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=./vsaspdotnet.PublishSettings
# publish to Azure App Service
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: VSHelloWorld # Replace with your app name
        publish-profile: ${{ secrets.publish_profile }} # Define secret variable in repository settings as per action documentation
        package: './vsaspnetmvcappPP' 

    - name: 'Upload Package'
      uses: actions/upload-artifact@v1
      with:
        name: BuildArtifacts
        path: aspnetmvcapp
